Let us know who you would like to hear on the show. Currently I'm still at the early stages of the working through the
logistical details of producing the show, but even if I don't get this off the ground, perhaps someone else can...
Nau mau haere mai whanau.
